name: Generate Changelog
description: 'Generate a changelog file using git-chglog push it to the repository'
runs:
  steps:
    - name: Generate Changelog
      run: |
        GIT_CHGLOG_VERSION=0.15.4
        curl -o git-chglog -L "https://github.com/git-chglog/git-chglog/releases/download/${GIT_CHGLOG_VERSION}/git-chglog_linux_amd64"
        chmod +x git-chglog
        ./git-chglog -o ${{ github.workspace }}-CHANGELOG.md
        rm git-chglog
    - name: Commit Changelog
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add ${{ github.workspace }}-CHANGELOG.md
        git commit -m "chore: update changelog"
        git push
